### ISSUE TITLE
more arrow separators?

### ISSUE THREAD

**Issue by longemen3000** [zdroid/ChemEquations.jl#1]
from Catalyst.jl, they use the [following arrows ](https://github.com/SciML/Catalyst.jl/blob/ac019b1ffd5d529241b9cebf9385e436b0f1eaed/src/reaction_network.jl#L56)for their DSL: (stored as a `Set{Symbol}` in catalyst, converted to `Vector{Char}` here)
```julia
fwd_arrows = ['>', '→', '↣', '↦', '⇾', '⟶', '⟼', '⥟', '⥟', '⇀', '⇁', '⇒', '⟾']
bwd_arrows = ['<', '←', '↢', '↤', '⇽', '⟵', '⟻', '⥚', '⥞', '↼', '↽', '⇐', '⟽']
double_arrows = ['↔', '⟷', '⇄', '⇆', '⇔', '⟺']
pure_rate_arrows = ['⇐', '⟽', '⇒', '⟾', '⇔', '⟺']
equal_sign = ['='] #not used in catalyst, but used here 
```
defining:
```julia
const EQUALCHARS = vcat(fwd_arrows,bwd_arrows,double_arrows,pure_rate_arrows,equal_sign)
```
would extend automatically the amount of separators used.

**Comment by longemen3000** [comment]
the julia parser, [as of 1.6](https://github.com/JuliaLang/julia/pull/36729/),  supports the following arrows :
```
(← → ↔ ↚ ↛ ↞ ↠ ↢ ↣ ↦ ↤ ↮ ⇎ ⇍ ⇏ ⇐ ⇒ ⇔ ⇴ ⇶ ⇷ ⇸ ⇹ ⇺ ⇻ ⇼ ⇽ ⇾ ⇿ ⟵ ⟶ ⟷ ⟹ ⟺ ⟻ ⟼ ⟽ ⟾ ⟿ ⤀ ⤁ ⤂ ⤃ ⤄ ⤅ ⤆ ⤇ ⤌ ⤍ ⤎ ⤏ ⤐ ⤑ ⤔ ⤕ ⤖ ⤗ ⤘ ⤝ ⤞ ⤟ ⤠ ⥄ ⥅ ⥆ ⥇ ⥈ ⥊ ⥋ ⥎ ⥐ ⥒ ⥓ ⥖ ⥗ ⥚ ⥛ ⥞ ⥟ ⥢ ⥤ ⥦ ⥧ ⥨ ⥩ ⥪ ⥫ ⥬ ⥭ ⥰ ⧴ ⬱ ⬰ ⬲ ⬳ ⬴ ⬵ ⬶ ⬷ ⬸ ⬹ ⬺ ⬻ ⬼ ⬽ ⬾ ⬿ ⭀ ⭁ ⭂ ⭃ ⭄ ⭇ ⭈ ⭉ ⭊ ⭋ ⭌ ￩ ￫ ⇜ ⇝ ↜ ↝ ↩ ↪ ↫ ↬ ↼ ↽ ⇀ ⇁ ⇄ ⇆ ⇇ ⇉ ⇋ ⇌ ⇚ ⇛ ⇠ ⇢ ↷ ↶ ↺ ↻ <-- <-->)
```
in julia 1.6, the strings `<--` and `<-->` are supported as symbols, (other arrows are invalid julia parser notation). here, as there are only string manipulation, is ok to have also `<-`,`->`, `-->`, and `<->` as valid separators, but they are strings, so they can't be stored in `EQUALCHARS `, maybe adding a second vector  `EQUALSTRINGS` and adding those there?

**Comment by zlatanvasovic** [comment]
@longemen3000 I added all those characters. Although it seems even Catalyst was missing some characters: https://github.com/SciML/Catalyst.jl/pull/235.

This is an idea for strings that may split the equation:
```julia
"Strings split a chemical equation into two sides."
const EQUALSTRINGS = [":=", "::=", "=:" , "<=", "<=>", "=>", "<--", "<-->", "-->", "<-", "<->", "->"]
```
